resources:
  - ../../base
namespace: prod
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: increase-memory.yaml
- path: increase-replica.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: my-nginx
  path: json-patch.yaml
    
