resources:
- deployment.yaml
namespace: my-namespace
namePrefix: prod-
nameSuffix: "-007"
labels:
  - pairs:
      app: prod-app
    includeSelectors: true 
commonAnnotations:
  oncallPager: 800-555-1212