apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  template:
    spec:
      containers:
        - name: container-1
          image: nginx
          env:
            - name: environment
              value: "dev"
        - name: container-2
          image: nginx
          env:
            - name: git-branch
              value: "dev"
